// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYcSyIt_rJ3wvMCiDg_L10AjYwlKNK61s',
    appId: '1:32781420828:web:815c0f926ebffe325dd2d9',
    messagingSenderId: '32781420828',
    projectId: 'sunat-flutter-app-caa2f',
    authDomain: 'sunat-flutter-app-caa2f.firebaseapp.com',
    storageBucket: 'sunat-flutter-app-caa2f.appspot.com',
    measurementId: 'G-T19DTG98BZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfRd3E28B0V3pTl6DoVndvce0uadinXp8',
    appId: '1:32781420828:android:d837ba93205bb81f5dd2d9',
    messagingSenderId: '32781420828',
    projectId: 'sunat-flutter-app-caa2f',
    storageBucket: 'sunat-flutter-app-caa2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk2SonocYGYfxK97Qe83Q3IxDLzZVwOZM',
    appId: '1:32781420828:ios:1ca3c7cb03df08a55dd2d9',
    messagingSenderId: '32781420828',
    projectId: 'sunat-flutter-app-caa2f',
    storageBucket: 'sunat-flutter-app-caa2f.appspot.com',
    iosClientId: '32781420828-j54302r2fmj53mb4eu7ftcmsc3nj10tg.apps.googleusercontent.com',
    iosBundleId: 'com.example.sunatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk2SonocYGYfxK97Qe83Q3IxDLzZVwOZM',
    appId: '1:32781420828:ios:1ca3c7cb03df08a55dd2d9',
    messagingSenderId: '32781420828',
    projectId: 'sunat-flutter-app-caa2f',
    storageBucket: 'sunat-flutter-app-caa2f.appspot.com',
    iosClientId: '32781420828-j54302r2fmj53mb4eu7ftcmsc3nj10tg.apps.googleusercontent.com',
    iosBundleId: 'com.example.sunatApp',
  );
}
